### ISSUE TITLE
Support BatchSize when Find

### ISSUE THREAD

**Issue by jiangz222** [qiniu/qmgo#103]
Limit is the total number of results you want. If your query would return one thousand documents but you only want 5 you can use Limit to limit the size of the total result.

BatchSize is the number of results that should be returned in each batch. If your result set for a query is large MongoDB isn't going to return all the results in one batch. It will return a subset of the total result, then the cursor will send a getMore message to the server when it needs the next batch of results.

**Comment by codenoid** [comment]
I will try to work on this
