### ISSUE TITLE
Database support RunCommand

### ISSUE THREAD

**Issue by jiangz222** [qiniu/qmgo#111]
Like mongoDB official driver did!

**Comment by piaoger** [comment]
oops，It's a block issue for me to migrate projects built on mgo.
What's the planning of this issue? @jiangz222

**Comment by jiangz222** [comment]
> oops，It's a block issue for me to migrate projects built on mgo.
> What's the planning of this issue? @jiangz222
Maybe this weekend!

**Comment by piaoger** [comment]
waiting waiting for you :)
