### ISSUE TITLE
time.Time 读出时间差8小时，有办法统一处理吗？

### ISSUE THREAD

**Issue by 15951836388** [qiniu/qmgo#123]
time.Time 读出时间差8小时，有办法统一处理吗

**Comment by jiangz222** [comment]
@15951836388 
你需要贴一下你的最简单的测试代码，以及提供一下qmgo版本号

**Comment by 15951836388** [comment]
之前说错了，time.Time ，读写 没问题。 只是再读出来，差8小时。希望读出来和写进去的值一样，有办法吗？

**Comment by xen0n** [comment]
时区问题，自己 `t.In(time.Local)` 这种方法处理一下可行否？

**Comment by xen0n** [comment]
@15951836388 有后续么？

数据库查询统一返回 UTC 可以适应各种场景（归根结底时区这件事情，业务层是应当感知的），这也是 [globalsign/mgo 做这个更改](https://github.com/globalsign/mgo/pull/42) 的原因。如果可以解决你的问题最好。

**Comment by 15951836388** [comment]
没有解决。存进去的是什么，读出来的就应该是什么。

如果一个很复杂的角色对象数据，在业务层每次都要额外处理，心里负担，也是不太适合的。还是希望能有办法统一处理。

**Comment by jiangz222** [comment]
遵循MongoDB官方driver和 globalsign/mgo 行为，我们暂时不对时区做处理了，保持UTC

**Comment by 888go** [comment]
> @15951836388 有后续么？
> 
> 数据库查询统一返回 UTC 可以适应各种场景（归根结底时区这件事情，业务层是应当感知的），这也是 [globalsign/mgo 做这个更改](https://github.com/globalsign/mgo/pull/42) 的原因。如果可以解决你的问题最好。

国情不一样吧. 国内的谁看utc时间. 如果只面对国内的业务, 再弄个utc就没必要了.

**Comment by xen0n** [comment]
> 如果只面对国内的业务

后续万一业务发生扩展，而系统没有提前「麻烦」一点，那会有得好受，不要问我（们）怎么知道的 ;-)
