### ISSUE TITLE
Split the hook interfaces into one hook only?

### ISSUE THREAD

**Issue by LowryTang** [qiniu/qmgo#124]
The current Hook interface is coupled with before and after. Can you split them into only one hook function? With this, I don't have to create the dummy hook for after hook sometimes.

For example
```

type InsertHook interface {
	BeforeInsert() error
	AfterInsert() error
}

// new interface
type BeforeInsert interface {
	BeforeInsert() error
}
type AfterInsert interface {
	AfterInsert() error
}
```

**Comment by jiangz222** [comment]
Nice!
Got it!
