### ISSUE TITLE
uint32 and similar fields are always marshaled into BSON int64

### ISSUE THREAD

**Issue by xen0n** [qiniu/qmgo#132]
* ~There can be `nil` maps that break `reflect`-based setters like [mergo](https://github.com/imdario/mergo)~ #117
* It seems `uint32` is unconditionally marshaled into `NumberLong`, it breaks one of our in-house data extraction scripts. https://github.com/mongodb/mongo-go-driver/pull/193 (closed by upstream but has a workaround)

**Comment by xen0n** [comment]
N.B. These are actually `mongo-driver` bugs/features, but have caused actual pain in our transition away from `mgo`. I don't know if such shimming should be best done in `qmgo` proper.

**Comment by xen0n** [comment]
First one is dup of #117, updated parent comment.

**Comment by jiangz222** [comment]
[Record here](https://github.com/qiniu/qmgo/wiki/Differences-between-Qmgo-and-Mgo#data-is-different-in-mongodb)
Wait for official plan.

**Comment by xen0n** [comment]
For the time you can mass-update (or insert) `bson:"foo"` tags to look like `bson:"foo,minsize"`, for the affected fields, to maintain compatibility of stored data.

**Comment by lifegit** [comment]
excuse me, can you tell me how to use it?
[#117](https://github.com/qiniu/qmgo/issues/117)
