### ISSUE TITLE
建议使用 MarshalValueWithRegistry

### ISSUE THREAD

**Issue by Alomerry** [qiniu/qmgo#141]
https://github.com/qiniu/qmgo/blob/ad73f3e918704887eb993022239391c25f3fad88/query.go#L223

Marshal 时没有使用连接时定制的 Registry，建议保持一致。

**Comment by jiangz222** [comment]
> Marshal 时没有使用连接时定制的 Registry，建议保持一致。

没有特别明白你的意思，我看都是用`DefaultRegistry`呀？

**Comment by Alomerry** [comment]
> 没有特别明白你的意思，我看都是用`DefaultRegistry`呀？

场景是在 qmgo 连接 MongoDB 时自定义 Registry 做 encode 和 decode。但是 qmgo 的 distinct 函数中调用的 `bson.MarshalValue()`，该函数中使用了 mongo-driver 自带的  DefaultRegistry，而没有使用连接时我们自定义的 Registry。

**Comment by jiangz222** [comment]
> > 没有特别明白你的意思，我看都是用`DefaultRegistry`呀？
> 
> 场景是在 qmgo 连接 MongoDB 时自定义 Registry 做 encode 和 decode。但是 qmgo 的 distinct 函数中调用的 `bson.MarshalValue()`，该函数中使用了 mongo-driver 自带的 `DefaultRegistry`，而没有使用连接时我们自定义的 Registry，我们希望在 distinct 中的 marshal 和 unmarsh 依旧使用自定义的 Registry。

Fixed!
你们的使用结果也可以同步告诉我一下
