### ISSUE TITLE
Cursor Next 读取数据不可靠，有可能使用前一个对象的值

### ISSUE THREAD

**Issue by zxy198717** [qiniu/qmgo#149]
```golang
type Demo struct {
	Name    string       `bson:"name,omitempty"`
}

demo := Demo{}
for it.Next(&demo) {
    demos = append(demos, demo)
}
```

由于 demo 对象是重用的，name 没有值的有概率使用上一次的值。

有两种方式可以解决这个问题：

- 使用后重新初始化

    ```golang
    demo := Demo{}
    for it.Next(&demo) {
        demos = append(demos, demo)
        demo := Demo{}
    }
    ```

- Next  方法里统一处理，清掉 struct

	```golang
	func (c *Cursor) Next(result interface{}) bool {
		if c.err != nil {
			return false
		}
		var err error
		if c.cursor.Next(c.ctx) {
			p := reflect.ValueOf(result).Elem()
			p.Set(reflect.Zero(p.Type()))
			err = c.cursor.Decode(result)
			if err == nil {
				return true
			}
		}
		return false
	}
	```

https://github.com/qiniu/qmgo/blob/1472099f6cd6832694e1062413d97d174ba2c807/cursor.go#L31

第一种方式对开发要求较高，写的时候要记得有这件事，容易遗漏。

第二种方式比较简单，但比较隐晦，不知是否合理，希望能给一下建议。

**Comment by jiangz222** [comment]
Nice One！

这个问题抽象一下，在不同场景下可能会有不同的答案。

在`MongoDB`和你的预设前提下，答案我觉得是要外部处理，不应该`qmgo`内部处理。
1 首先`omitempty`，含义是不存在则忽略，对于被调用者`B(即Next())`的行为是符合omitempty的。
2 其次，就算没有`omitempty`, MongoDB的整体设计原则也是，只针对有效数据改写：
```go
type TestItem struct {
	Name string `bson:"name"`
	Age  int    `bson:"age"`
}

func TestOmit(t *testing.T) {
	cli := initClient("test")
	defer cli.Close(context.Background())
	defer cli.DropCollection(context.Background())

        // 只插入age，文档中不存在name
	cli.InsertOne(context.Background(), bson.M{"age": 18})

       // 用一个已经初始化了name的结构体去Find.One(&ot)
	ot := TestItem{Name: "Lucas", Age: 30} 
	cli.Find(context.Background(), bson.M{"age": 18}).One(&ot)
	fmt.Println(ot) 
        // output: {Lucas 18}. 因为DB文档里没有name的值，所以保留了调用前ot里Name的值
}
```

**Comment by zxy198717** [comment]
```golang
fmt.Println(ot) 
// output: {Lucas 18}. 因为DB文档里没有name的值，所以保留了调用前ot里Name的值
```

output 应该是写错了吧？

对于 Find 这样问题不大，但对于 Next 来说，绝大多数情况下，想要的是一个全新的零值对象，原来用的 mgo 没有此种表现，建议能处理下，要不然就又多了一个陷阱😜。

**Comment by jiangz222** [comment]
> ```go
> fmt.Println(ot) 
> // output: {Lucas 18}. 因为DB文档里没有name的值，所以保留了调用前ot里Name的值
> ```
> 
> output 应该是写错了吧？
> 
> 对于 Find 这样问题不大，但对于 Next 来说，绝大多数情况下，想要的是一个全新的零值对象，原来用的 mgo 没有此种表现，建议能处理下，要不然就又多了一个陷阱😜。

- Output是qmgo的UT的输出，没有错呀。
- 这个不涉及到是Find还是cursor的区别，下面都是走MongoDB的Unmarshal，MongoDB官方的go-client的总体Unmarshal逻辑都是如此。
- Mgo的行为不一致，我们不一定会跟随Mgo😂
- 个人觉得这是更简单的实现，这样把操作留在外部。如果驱动内部都清到默认值，外部想保留某些字段，就做不到了(除了自己做registry)

**Comment by zxy198717** [comment]
理解。

不过这个下面这个注释不是很理解，既然“保留了调用前ot里Name的值”，为啥输出没有 Name 呢？

```
fmt.Println(ot) 
// output: {Lucas 18}. 因为DB文档里没有name的值，所以保留了调用前ot里Name的值
```

**Comment by jiangz222** [comment]
> 理解。
> 
> 不过这个下面这个注释不是很理解，既然“保留了调用前ot里Name的值”，为啥输出没有 Name 呢？
> 
> ```
> fmt.Println(ot) 
> // output: {Lucas 18}. 因为DB文档里没有name的值，所以保留了调用前ot里Name的值
> ```

我用的是Println，所以`Key`没有输出，只输出了`name`的`value`: `Lucas`和`age`的`value`:`18`

**Comment by zxy198717** [comment]
... 抱歉，看错了。
