### ISSUE TITLE
Support estimatedDocumentCount

### ISSUE THREAD

**Issue by zxy198717** [qiniu/qmgo#150]
https://pkg.go.dev/go.mongodb.org/mongo-driver/mongo#Collection.EstimatedDocumentCount

Current count use aggregation, but `.count()` is by far faster.

- https://stackoverflow.com/questions/33181878/mongodb-count-vs-aggregation
- https://developer.mongodb.com/community/forums/t/about-golang-mongo-driver-countdocuments/8112/

**Comment by jiangz222** [comment]
Seems `EstimatedDocumentCount()` only count documents without filters, which is not the `count()` in Qmgo wants?
