### ISSUE TITLE
Is this project ready for production?

### ISSUE THREAD

**Issue by cupen** [qiniu/qmgo#152]
Hello! Is this project ready for production? 
If yes, some performance benchmarks would be good, and maybe I can give a hand.

**Comment by jiangz222** [comment]
> Hello! Is this project ready for production?
> If yes, some performance benchmarks would be good, and maybe I can give a hand.

Yes, the v1.0.0 is about to release this month, so I think `Qmgo` is almost ready for production.
Look forward for your contribution!

**Comment by jiangz222** [comment]
https://github.com/qiniu/qmgo/tree/v1.0.0
