### ISSUE TITLE
readme use function cli.Insert ,but  this function does not exist

### ISSUE THREAD

**Issue by kaiili** [qiniu/qmgo#155]
Both readme.md and readme_zh.md  have use code like this,
```
result, err := cli.Insert(ctx, userInfo)
```
but in the master branch, it seems that there is no insert function

**Comment by jiangz222** [comment]
> Both readme.md and readme_zh.md have use code like this,
> 
> ```
> result, err := cli.Insert(ctx, userInfo)
> ```
> 
> but in the master branch, it seems that there is no insert function

Change to `InsertOne`, thanks!
