### ISSUE TITLE
RunCommand problem

### ISSUE THREAD

**Issue by gogoods** [qiniu/qmgo#159]
qmgo:
![image](https://user-images.githubusercontent.com/3422759/109477944-9a379280-7ab3-11eb-9b22-c688472fd889.png)
![image](https://user-images.githubusercontent.com/3422759/109477956-9d328300-7ab3-11eb-9478-cbe02014495a.png)

mgo:
![image](https://user-images.githubusercontent.com/3422759/109477976-a3286400-7ab3-11eb-820e-2054ca123655.png)
![image](https://user-images.githubusercontent.com/3422759/109478011-ad4a6280-7ab3-11eb-938b-5cd338366124.png)

mgo's result is correct, qmgo is failed, why?

**Comment by jiangz222** [comment]
I think in your example, I think the `num` or `geoNear` are not valid command to run, you can test it with official mongoDB driver.
Mgo maybe wrapper the run command operation.
Following run command codes runs correcttly:
```
	opts := opts.RunCommandOptions{RunCmdOptions: options.RunCmd().SetReadPreference(readpref.Primary())}
	res := cli.RunCommand(context.Background(), bson.D{
		{"ping", 1}}, opts)
	ast.NoError(res.Err())
```
Feel free to reopen issue if you have any question.
