### ISSUE TITLE
请问mongo-driver能否做到: 查询出表中两个字段"a>b"的数据.

### ISSUE THREAD

**Issue by shenguanjiejie** [qiniu/qmgo#161]
![image](https://user-images.githubusercontent.com/9425605/109749709-24980780-7c16-11eb-8574-d18734272880.png)
由于qmgo基于mongo-driver, 所以经验证也是一样的结果.

**Comment by jiangz222** [comment]
100 和 "$b" 不是一个意思。如果b是一个int之类的类型，直接 `"$gt": b` 就行了
