### ISSUE TITLE
使用 DoTransaction 必须赋予 admin.root 权限，否则 transactionAllowed 检查无法通过

### ISSUE THREAD

**Issue by zhb127** [qiniu/qmgo#169]
### 环境说明

版本：docker mongo:4.2.6

### 问题描述

![image](https://user-images.githubusercontent.com/5210208/114661392-7eb5dd80-9d29-11eb-88b7-bb557ff83d35.png)

![image](https://user-images.githubusercontent.com/5210208/114661453-9c834280-9d29-11eb-8d5f-d579d22c44a8.png)

![image](https://user-images.githubusercontent.com/5210208/114661647-e704bf00-9d29-11eb-8a7d-bc6501d327a9.png)

### 期望结果

没必要前置检查 transactionAllowed，还指向 admin 数据库，一些有管控的公司，基本上不允许访问 admin 数据。

可以去掉 transactionAllowed 的判断，直接得到服务器的命令不支持错误提示更好。

**Comment by rekey** [comment]
这个有计划修正么，不修正简直用不了啊。

**Comment by zhb127** [comment]
> 这个有计划修正么，不修正简直用不了啊。

#170 PR 提交了更新，得看作者是否能通过了。

**Comment by jiangz222** [comment]
> > 这个有计划修正么，不修正简直用不了啊。
> 
> #170 PR 提交了更新，得看作者是否能通过了。

👍 
Thanks，it's in the latest release!

**Comment by rekey** [comment]
> > 这个有计划修正么，不修正简直用不了啊。
> 
> #170 PR 提交了更新，得看作者是否能通过了。

大佬给力。
