### ISSUE TITLE
No Document In Result

### ISSUE THREAD

**Issue by mztlive** [qiniu/qmgo#174]
`cli.Database("missamelle").Collection("t_user").Find(ctx, bson.M{"openID": openID}).One(&user)`

不好意思，打扰了。
我第一次使用MongoDB。我发现这里如果查询不到数据会返回一个 no document in result 的 error， 我想知道，one方法是只会返回这一种error 吗？ 如果是的话我将使用 if err != nil 来判断数据是否存在。

这是与其它mysql orm不太一样的地方。还望解答一下

**Comment by jiangz222** [comment]
no document只是找不到文档，只是错误的一种，会有很多的错误的

**Comment by mztlive** [comment]
那这样就会产生问题， 我想判断某个ID的数据是否存在，如果以&user的值为依据，那么就可能忽略error， 如果以error为依据，那么error又不能只表示数据不存在

```go
err := cli.Database("missamelle").Collection("d_user").Find(ctx, bson.M{"openID": openID}).One(&user)

	if err.Error() == "no document in result" {
		//这样来表示数据不存在？
	}
```

**Comment by mztlive** [comment]
> no document只是找不到文档，只是错误的一种，会有很多的错误的


那这样就会产生问题， 我想判断某个ID的数据是否存在，如果以&user的值为依据，那么就可能忽略error， 如果以error为依据，那么error又不能只表示数据不存在

```go
err := cli.Database("missamelle").Collection("d_user").Find(ctx, bson.M{"openID": openID}).One(&user)

if err.Error() == "no document in result" {
      //这样来表示数据不存在？
}
```

**Comment by mztlive** [comment]
> no document只是找不到文档，只是错误的一种，会有很多的错误的

![image](https://user-images.githubusercontent.com/13467892/119260765-d5ef7d80-bc06-11eb-9841-f2ff192c88b6.png)

还有更合适的做法吗？

**Comment by mztlive** [comment]
> no document只是找不到文档，只是错误的一种，会有很多的错误的

```go
if err != nil {
      //属于用户不存在的情况
      if err.Error() == "no document in result" {
	      user, err = that.registerFromOpenID(ctx, session.OpenID)
	      if err != nil {
		      return "", nil
	      }
      } else {
	      //属于其它情况， 写点日志
      }
}
```

还有更合适的做法吗？

**Comment by BeanWei** [comment]
你这搞法不对啊，mongo 有开放判断 err 的类型不是你这样写硬编码

**Comment by mztlive** [comment]
> 你这搞法不对啊，mongo 有开放判断 err 的类型不是你这样写硬编码

不好意思，我第一次用，能发一下文档地址吗？ 谢谢

**Comment by BeanWei** [comment]
好像这里面的单测有吧，没有的话就去看官方仓库的例子

**Comment by mztlive** [comment]
> 好像这里面的单测有吧，没有的话就去看官方仓库的例子

好的，谢谢
