### ISSUE TITLE
How to create hashed index?

### ISSUE THREAD

**Issue by liyuliang2013** [qiniu/qmgo#180]
`{Key: []string{"$hashed:oss_id"}}`

I have try the `mgo` code style but it's failed

`<MongoDB.C>:  book  Index:  [{[$hashed:oss_id] false false false <nil>}]  error:  (CannotCreateIndex) Error in specification { key: { $hashed:oss_id: 1 }, background: false, name: "$hashed:oss_id_1", sparse: false, unique: false } :: caused by :: Index key contains an illegal field name: field name starts with '$'. res:  []
panic: (CannotCreateIndex) Error in specification { key: { $hashed:oss_id: 1 }, background: false, name: "$hashed:oss_id_1", sparse: false, unique: false } :: caused by :: Index key contains an illegal field name: field name starts with '$'.
`

**Comment by jiangz222** [comment]
You mean hash index?
`db.collection.createIndex({ _id:"hashed"})`

Or please show your codes? According to your logs, `field name starts with '$'` is the reason
