### ISSUE TITLE
如何同时更新多条文档

### ISSUE THREAD

**Issue by xgzlucario** [qiniu/qmgo#181]
如何同时更新多条文档，每条文档对应的改动均不相同？

**Comment by xgzlucario** [comment]
像这样：
UPDATE Person 
SET FirstName = Fred WHERE LastName = Wilson
SET FirstName = Alan WHERE LastName = Bob
...

**Comment by jiangz222** [comment]
https://github.com/qiniu/qmgo/blob/master/bulk_test.go
