### ISSUE TITLE
查询提示not enough arguments

### ISSUE THREAD

**Issue by cmkcmk181** [qiniu/qmgo#194]
按照示例出现not enough arguments错

代码片段如下：
ctx := context.Background()
	cli, err := qmgo.Open(ctx,
		&qmgo.Config{
			Uri: "mongodb://localhost:27017",
			Database: "homfan-master",
			Coll: "tenant_info",
			Auth: &qmgo.Credential{
				Username: "root",
				Password: "123456",
			},
		})
	one := entity.TenantInfoEntity{}
	cli.Find(ctx,bson.M{"id":1}).One(&one)
调用 Find报错：not enough arguments

go 版本：1.16
mongo-driver: v1.7.1
qmgo v1.0.1

**Comment by jiangz222** [comment]
Hi, please paste the codes that can be run.

**Comment by jiangz222** [comment]
Please feel free to reopen issue.
