### ISSUE TITLE
Bad field type uint64 [recovered]

### ISSUE THREAD

**Issue by milosrs** [qiniu/qmgo#206]
I have this code:

```
type Account struct {
	UserID uint64	                   'bson:"userid" validate:"required,unique"'
	Assets map[int]*myStruct   'bson:"assetbalance"'
}
```

When trying to execute this piece of code:

```
func (r *AccountRepository) CreateAccount(account broker_account.Account) error {
	ctx, cancel := context.WithTimeout(context.Background(), timeoutDuration)
	defer cancel()

	_, insertErr := r.cli.InsertOne(ctx, account)

	return insertErr
}
```

I'm getting the following error: 

```
panic: Bad field type uint64 [recovered]
        panic: Bad field type uint64
```

Can you tell me if I'm doing something wrong? This has started happening when I added the `unique` validation annotation.

**Comment by jiangz222** [comment]
> I have this code:
> 
> ```
> type Account struct {
> 	UserID uint64	                   'bson:"userid" validate:"required,unique"'
> 	Assets map[int]*myStruct   'bson:"assetbalance"'
> }
> ```
> 
> When trying to execute this piece of code:
> 
> ```
> func (r *AccountRepository) CreateAccount(account broker_account.Account) error {
> 	ctx, cancel := context.WithTimeout(context.Background(), timeoutDuration)
> 	defer cancel()
> 
> 	_, insertErr := r.cli.InsertOne(ctx, account)
> 
> 	return insertErr
> }
> ```
> 
> I'm getting the following error:
> 
> ```
> panic: Bad field type uint64 [recovered]
>         panic: Bad field type uint64
> ```
> 
> Can you tell me if I'm doing something wrong? This has started happening when I added the `unique` validation annotation.

Hi，I think `unique` is for checking the unique values in slice or map, you can check more to [go-playground/validator](https://github.com/go-playground/validator)
