### ISSUE TITLE
_

### ISSUE THREAD

**Issue by jackwiy** [qiniu/qmgo#208]

**Comment by jiangz222** [comment]
> @jiangz222 问题描述：默认字段_id，createAt、updateAt没有获得预期效果。 得到的效果：{ _id: ObjectId('000000000000000000000000') 预期的效果：{"_id" : ObjectId("6167d3605c5deb4e6fc58526")}
> 
> 经过排查，是由于qiniu/qmgo包time.Now()获取的时间不对导致. 但我在qiniu/qmgo包的外部代码调用是正常的时间，但qiniu/qmgo包内部获取时间不正确，导致000.
> 
> ```
> import (
> 	"time"
> 
> 	"github.com/qiniu/qmgo/field"
> 	"go.mongodb.org/mongo-driver/bson/primitive"
> )
> 
> type Model struct {
> 	field.DefaultField `bson:",inline"`
>         // Id  primitive.ObjectID `json:"id" bson:"_id,omitempty"`
> ```
> 
> 引用包的相关文件： https://github.com/qiniu/qmgo/blob/master/field/default_field.go
> 
> ```
> // DefaultCreateAt changes the default _id field
> func (df *DefaultField) DefaultId() {
> 	if df.Id.IsZero() {
> 		df.Id = primitive.NewObjectID()
> 	}
> }
> ```
> 
> https://github.com/mongodb/mongo-go-driver/blob/master/bson/primitive/objectid.go
> 
> ```
> // NewObjectID generates a new ObjectID.
> func NewObjectID() ObjectID {
> 	return NewObjectIDFromTimestamp(time.Now())
> }
> ```

麻烦贴一个最小化的可运行代码？因为当前我们UT里的相关测试都是可以通过的。无法佐证你描述的问题
