### ISSUE TITLE
How to use $lookup through bson.m {} ?

### ISSUE THREAD

**Issue by jackwiy** [qiniu/qmgo#211]

**Comment by jiangz222** [comment]
Can you do it by mongoDB shell?

**Comment by jackwiy** [comment]
@jiangz222 

It is able to get data through the shell.

```
db.getCollection('gallery').aggregate([{
   $lookup:
     {
       from: 'user',
       localField: 'user_id',
       foreignField: '_id',
       as: 'user'
     }
    }])
```

![image](https://user-images.githubusercontent.com/5044378/141074887-2a5f38b1-bfa6-4774-aec5-90c394edb3f5.png)

**Comment by jackwiy** [comment]
@jiangz222 

Or give an example of bson.D{}

When the braces are nested too much, it is easy to get dizzy.

![image](https://user-images.githubusercontent.com/5044378/141076741-913cecf8-61d7-479a-aaf8-25af5a92a631.png)

**Comment by jiangz222** [comment]
> @jiangz222
> 
> It is able to get data through the shell.
> 
> ```
> db.getCollection('gallery').aggregate([{
>    $lookup:
>      {
>        from: 'user',
>        localField: 'user_id',
>        foreignField: '_id',
>        as: 'user'
>      }
>     }])
> ```
> 
> ![image](https://user-images.githubusercontent.com/5044378/141074887-2a5f38b1-bfa6-4774-aec5-90c394edb3f5.png)

You miss the `filter` in shell？

**Comment by jackwiy** [comment]
@jiangz222 
You miss the filter in shell？

It is able to get data through the shell.

![image](https://user-images.githubusercontent.com/5044378/141435857-5dde45ed-0139-43a5-93b9-a052d2721436.png)

**Comment by jiangz222** [comment]
> @jiangz222 You miss the filter in shell？
> 
> It is able to get data through the shell.
> 
> ![image](https://user-images.githubusercontent.com/5044378/141435857-5dde45ed-0139-43a5-93b9-a052d2721436.png)

我的意思，你说qmgo的问题时，有这个filter，但是你的shell里没有？不能做类比
另外建议多贴代码，截图不好讨论问题
![image](https://user-images.githubusercontent.com/3799367/141478087-bac9023a-a69e-425a-9532-b359d51c8f7a.png)
