### ISSUE TITLE
Support options in database operation

### ISSUE THREAD

**Issue by Jweein** [qiniu/qmgo#212]
I have a server that requires data (which requires Primary ReadPreference), but also serves many Changestreams across multiple different collections (SecondaryPreferred would be the preferred ReadConcern here).

Would maintaining two clients, one with ReadPref Primary and one with ReadPref SecondaryPreferred?, be the best way to handle this? Or does qmgo have a more elegant way of handling this?

**Comment by jiangz222** [comment]
According to my understanding, one `read preference` for one client, so `two clients` may be the best solution.

**Comment by Jweein** [comment]
> two
    in mongo driver you can do this， but  qmgo client not support  options
	secondary := readpref.Secondary()
	dbOpts := options.Database().SetReadPreference(secondary)
	colltion := mongo.Client.Database(db, dbOpts).Collection(coll)
  
      // Database create connection to database
     func (c *Client) Database(name string) *Database {
	return &Database{database: c.client.Database(name), registry: c.registry}
     }

**Comment by Jweein** [comment]
> According to my understanding, one `read preference` for one client, so "two clients" may be the best solution 😄.

in mongo driver you can do this， but qmgo client not support options
secondary := readpref.Secondary()
dbOpts := options.Database().SetReadPreference(secondary)
colltion := mongo.Client.Database(db, dbOpts).Collection(coll)

  // Database create connection to database
 func (c *Client) Database(name string) *Database {
return &Database{database: c.client.Database(name), registry: c.registry}
 }

**Comment by jiangz222** [comment]
> > According to my understanding, one `read preference` for one client, so "two clients" may be the best solution 😄.
> 
> in mongo driver you can do this， but qmgo client not support options secondary := readpref.Secondary() dbOpts := options.Database().SetReadPreference(secondary) colltion := mongo.Client.Database(db, dbOpts).Collection(coll)
> 
> // Database create connection to database func (c *Client) Database(name string) *Database { return &Database{database: c.client.Database(name), registry: c.registry} }

You are right, we can add the `read preference` to database operation in qmgo.
Is `one-client-with-two-database-instance` the best way you want?

**Comment by Jweein** [comment]
> > > According to my understanding, one `read preference` for one client, so "two clients" may be the best solution 😄.
> > 
> > 
> > in mongo driver you can do this， but qmgo client not support options secondary := readpref.Secondary() dbOpts := options.Database().SetReadPreference(secondary) colltion := mongo.Client.Database(db, dbOpts).Collection(coll)
> > // Database create connection to database func (c *Client) Database(name string) *Database { return &Database{database: c.client.Database(name), registry: c.registry} }
> 
> You are right, we can add the `read preference` to database operation in qmgo. Is `one-client-with-two-database-instance` the best way you want?

That's what I need，but I'm not familiar with qmgo，I'm learning this。

**Comment by jiangz222** [comment]
`Database(name)` to `Database(name, options)`

**Comment by jiangz222** [comment]
> > > > According to my understanding, one `read preference` for one client, so "two clients" may be the best solution 😄.
> > > 
> > > 
> > > in mongo driver you can do this， but qmgo client not support options secondary := readpref.Secondary() dbOpts := options.Database().SetReadPreference(secondary) colltion := mongo.Client.Database(db, dbOpts).Collection(coll)
> > > // Database create connection to database func (c *Client) Database(name string) *Database { return &Database{database: c.client.Database(name), registry: c.registry} }
> > 
> > 
> > You are right, we can add the `read preference` to database operation in qmgo. Is `one-client-with-two-database-instance` the best way you want?
> 
> That's what I need，but I'm not familiar with qmgo，I'm learning this。

Thanks!
I change this issue's title and make it as a `feature`
