### ISSUE TITLE
Does CreateIndexes support the PartialFilterExpression option?

### ISSUE THREAD

**Issue by owllyi** [qiniu/qmgo#225]
When creating an index, I need to support PartialFilterExpression, for example, it will only be created if it is greater than a certain value

**Comment by jiangz222** [comment]
- Support [all indexOptions ](https://pkg.go.dev/go.mongodb.org/mongo-driver/mongo/options#IndexOptions) in `IndexModel`
- May consider more elegant way to implement `IndexModel`.

**Comment by owllyi** [comment]
Thanks~
Waiting for the new features.
