### ISSUE TITLE
查询条件的key能否和结构体的属性绑定，用反射或者代码生成，硬编码是数据库操作的一个痛点

### ISSUE THREAD

**Issue by zundaren** [qiniu/qmgo#249]
coll.Find(ctx, bson.M{"name": "cuk2"}).One(&u)

type UserInfo struct {
	Name string `bson:"name"`
	Age int 	`bson:"age"`
}

期望通过UserInfo.FieldName形式就能获取到对应的name
u：= UserInfo{}
coll.Find(ctx, bson.M{u.FieldName: "cuk2"}).One(&u)

**Comment by jiangz222** [comment]
首先，你的意思是要
```go
u：= UserInfo{}
coll.Find(ctx, bson.M{u.Name.FieldName: "cuk2"}).One(&u)
```
然后你这是一个很hack的需求，不适合在qmgo这样的DB driver做，可能需要另外写个包来试试😄
