### ISSUE TITLE
更新操作UpdateOne 没有更新default field里面的updateAt

### ISSUE THREAD

**Issue by shanhuang94** [qiniu/qmgo#272]
项目需求需要增删改查记录，发现新增的时候InsertOne 是OK的，createAt和updateAt 都更新为当前时间，
![image](https://user-images.githubusercontent.com/37739323/210695757-7e340bea-4208-4fe1-a417-93b3e5cbcbb9.png)
但是当执行更新操作UpdateOne的时候，代码如下
![image](https://user-images.githubusercontent.com/37739323/210696668-ddc1168c-9ad3-4d17-86e1-1889ed450d47.png)
数据库里面更新时间没有变化
![image](https://user-images.githubusercontent.com/37739323/210696772-59e80dac-0186-472e-abd1-b5002608bf05.png)

请问是我的用法不对还是这里本身就有问题，我看官网文档上说这里是自动支持的
![image](https://user-images.githubusercontent.com/37739323/210696887-bf989555-8e2c-4629-a4aa-137cf7064bb6.png)

另外发现用ReplaceOne方法的时候，更新时间会更新到最新时间，但是创建时间又给置空了，有点困惑，麻烦解答一下，感谢🙏

**Comment by jiangz222** [comment]
Please check the [Limitation of `default filed`](https://github.com/qiniu/qmgo/wiki/Automatically-update-fields#default-fields)
