### ISSUE TITLE
default field 里面的时间是iso标准，返回比中国时间晚8小时

### ISSUE THREAD

**Issue by shanhuang94** [qiniu/qmgo#274]
default field 里面的时间是iso标准，返回比中国时间晚8小时，难道返回列表的时候都要自己重新处理成中国标准时间吗，有什么解决办法吗

**Comment by jiangz222** [comment]
写进去是有时区信息的
你想说的是读出来的时候是没有时区信息吧？这个是使用了默认官方行为
