### ISSUE TITLE
查询FindOne结果是否为空，如何判断

### ISSUE THREAD

**Issue by Unique0071** [qiniu/qmgo#277]
按照官方文档：   
 // find one document
one := UserInfo{}
err = cli.Find(ctx, bson.M{"name": userInfo.Name}).One(&one)

如何区分：err是查询错误还是Document不存在呢？

如果err为空，是否one一定有值？

我目前使用的办法是：
在查询后，使用 `one.IsEmpty()`来判断是否取到用户
```
func (u UserInfo) IsEmpty() bool {
	return reflect.DeepEqual(u, UserInfo{})
}
```
不知道还有没有更准确的直接的办法

**Comment by xsean2020** [comment]
err == mongo.ErrNoDocuments
