### ISSUE TITLE
怎么直接在框架中使用mongodb的语句,比如show dbs 这个命令怎么在框架中体现

### ISSUE THREAD

**Issue by hxdyjx** [qiniu/qmgo#292]
怎么直接在框架中使用mongodb的语句,比如show dbs 这个命令怎么在框架中体现

**Comment by jiangz222** [comment]
Please check [RunCommand](https://github.com/qiniu/qmgo/blob/41996445c7d6b3004ad29667fc297200cf9aba52/database.go#L65)
