### ISSUE TITLE
性能是否有优化

### ISSUE THREAD

**Issue by Nyx2022** [qiniu/qmgo#302]
qmgo的作者你好，我看到此库是基于mongo官方driver的优化，但是readme里面主要讲的是用法的优化，想问一下，此库在官方驱动的基础上有做任何关于性能和资源占用的优化吗？

**Comment by jiangz222** [comment]
性能方面还没有优化，当前可以认为性能等价于mongo官方driver

**Comment by Nyx2022** [comment]
> 性能方面还没有优化，当前可以认为性能等价于mongo官方driver

后续有性能优化计划吗

**Comment by cupen** [comment]
> > 性能方面还没有优化，当前可以认为性能等价于mongo官方driver
> 
> 后续有性能优化计划吗？特别是内存占用方面

…… 欢迎提 PR，欢迎提赞助，欢迎提建议。 你如果对优化有想法，就提具体点的，具体怎样的内存占用？ 有可重现的例子不？

**Comment by 888go** [comment]
> > 性能方面还没有优化，当前可以认为性能等价于mongo官方driver
> 
> 后续有性能优化计划吗？特别是内存占用方面

MongoDB本身的内存占用? 这只是加一层皮而已, 咋优化?
