### ISSUE TITLE
qmgo.Open(), 直接放在min() 方法外面可以吗, 会有并发问题吗?

### ISSUE THREAD

**Issue by 888go** [qiniu/qmgo#313]
全局并发用一个连接可以吗, 怎么才能防止并发冲突.  

var ctx = context.Background()
var client, _ = qmgo.Open(ctx, &qmgo.Config{Uri: "mongodb://mongo_DibRHZ:11@124.220.182.235:27017"})

func main() {
	var one bson.M
	//假如此处并发查询修改会有问题吗? 还是应该每个协程都qmgo.Open()下?
	client.Find(ctx, bson.M{"tags": "database"}).One(&one)
}

**Comment by 888go** [comment]
这里, 回复下, 确定是并发安全的, 作者群里回复的. 
![微信截图_20240220095515](https://github.com/qiniu/qmgo/assets/43518669/2f8b89b9-35c8-4bfd-82aa-4648a79d2932)

**Comment by jiangz222** [comment]
不会
