### ISSUE TITLE
如何拦截mongo sql，以实现数据权限

### ISSUE THREAD

**Issue by bugKai001** [qiniu/qmgo#317]
求指教

**Comment by 888go** [comment]
你拦截mongo做啥, 实现权限应该是软件的问题, 没人权限放在MongoDB上折腾. 你找个gin的视频教程去啃下吧.

**Comment by bugKai001** [comment]
我的想法是通过拦截语句，增加filter过滤条件，跟gin没关系






------------------ 原始邮件 ------------------
发件人: 888go ***@***.***&gt;
发送时间: 2024年6月1日 08:50
收件人: qiniu/qmgo ***@***.***&gt;
抄送: Kevin Wei ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [qiniu/qmgo] 如何拦截mongo sql，以实现数据权限 (Issue #317)





 
你拦截mongo做啥, 实现权限应该是软件的问题, 没人权限放在MongoDB上折腾. 你找个gin的视频教程去啃下吧.

**Comment by 888go** [comment]
![微信截图_20240605180022](https://github.com/qiniu/qmgo/assets/43518669/c6955c11-f675-455f-9a9f-534e018fecc1)

用hook?
