### ISSUE TITLE
mgo user pay close attention

### ISSUE THREAD

**Issue by echoiron** [qiniu/qmgo#42]

**Comment by echoiron** [comment]
is there a better connection pool support?

**Comment by jiangz222** [comment]
> is there a better connection pool support?

Thanks.
The official mongo driver manage connection pool internally, so do `qmgo`.
You can create connection by config `MaxPoolSize` in `qmgo.Config`.
If you don't config `MaxPoolSize`, the default pool size is 100.

**Comment by jiangz222** [comment]
> is there a better connection pool support?

Many users asked this question, I think it's better to add it in README, thanks!

**Comment by scbizu** [comment]
If we have a monitor with [mgo connection pool stats](https://github.com/go-mgo/mgo/blob/v2-unstable/stats.go) before , it will be dropped after we migrate mgo to qmgo since qmgo uses the official mongo driver .

**Comment by jiangz222** [comment]
> If we have a monitor with [mgo connection pool stats](https://github.com/go-mgo/mgo/blob/v2-unstable/stats.go) before , it will be dropped after we migrate mgo to qmgo since qmgo uses the official mongo driver .

mongo-go-driver have a looking-good [monitor implement](https://github.com/mongodb/mongo-go-driver/blob/master/event/monitoring.go#L89).
And it's a callback, which I think it better than poll `mgo` stats.

**Comment by scbizu** [comment]
Will qmgo wrap this callback at the top of the application layer code  or we still need to do that by ourselves ？

**Comment by jiangz222** [comment]
> Will qmgo wrap this callback at the top of the application layer code or we still need to do that by ourselves ？

I prefer following lightweight way.
Sure, you can use it from `qmgo`.
please share your opinion.

```go
import (
	"context"
	"fmt"
	"testing"

	"github.com/qiniu/qmgo"
	"go.mongodb.org/mongo-driver/event"
)

func TestEvent(t *testing.T) {
	poolMonitor := &event.PoolMonitor{
		Event: func(evt *event.PoolEvent) {
			switch evt.Type {
			case event.GetSucceeded:
				fmt.Println("get successed")
			case event.ConnectionReturned:
				fmt.Println("connsCheckedOut")
			}
		},
	}
	clientOpts := &qmgo.Config{
		Uri:         "mongodb://localhost:27017",
		PoolMonitor: poolMonitor,
	}
	cli, err := qmgo.Open(context.Background(), clientOpts)
}
```

**Comment by scbizu** [comment]
Cool ~ Thank you

**Comment by jiangz222** [comment]
> Cool ~ Thank you

🤝 
Just try `qmgo`
