### ISSUE TITLE
希望可以支持map[int]和time.Time的读写

### ISSUE THREAD

**Issue by 15951836388** [qiniu/qmgo#46]
map[intXX]intxx   map的key和val ，是各种非string类型

**Comment by jiangz222** [comment]
> map[intXX]intxx map的key和val ，是各种非string类型

这不是天然就支持吗？
或者你举例子一下？

**Comment by 15951836388** [comment]
我记得官方的驱动。

map，只支持 map[string]string ，不支持非string的内容

而且 time.Time 无法读写

**Comment by jiangz222** [comment]
> 我记得官方的驱动。
> 
> map，只支持 map[string]string ，不支持非string的内容
> 
> 而且 time.Time 无法正常读写

不会，都是支持的
