### ISSUE TITLE
实际使用中，需要类似的封装吗？

### ISSUE THREAD

**Issue by 15951836388** [qiniu/qmgo#48]
![image](https://user-images.githubusercontent.com/14047483/90208111-98a9c400-de1a-11ea-9056-07334d9bafbd.png)
如果确实需要的话，希望qmgo可以提供个 最佳的封装实践，免得大家各自重新造轮子

**Comment by jiangz222** [comment]
driver是不适合封装的这个的
- 我理解一般正确的姿势，是在FindOne外面建立链接(Connect)，Find只管Find的逻辑
- 不太明白你的使用场景， 不过一般而言，也不应该每做一个CRUD操作都建链/关链一次

**Comment by 15951836388** [comment]
mgo里Connect是可以clone的，推荐用法是 每次 clone close

你的意思，公用全局一个Connect，不关闭？
大量并发读写时，一个Connect，够用吗？

**Comment by jiangz222** [comment]
> mgo里Connect是可以clone的，推荐用法是 每次 clone close
> 
> 你的意思，公用全局一个Connect，不关闭？
> 大量并发读写时，一个Connect，够用吗？

可以吧， 这不就是初始化connect时，可以指定连接池的意义吗？
