### ISSUE TITLE
Doesn't qmgo have dropindex?

### ISSUE THREAD

**Issue by echoiron** [qiniu/qmgo#49]
![image](https://user-images.githubusercontent.com/52339367/90211213-afecaf80-de22-11ea-807d-130d49e97c63.png)

**Comment by jiangz222** [comment]
Maybe support this weekend.
You can try and submit PR too. 😃 
Thanks

**Comment by jiangz222** [comment]
welcome to wechat group

![avatar](http://pgo8q04yu.bkt.clouddn.com/qmgoG)
