### ISSUE TITLE
Hope qmgo adds bulk batch processing

### ISSUE THREAD

**Issue by echoiron** [qiniu/qmgo#50]
![image](https://user-images.githubusercontent.com/52339367/90211804-52f1f900-de24-11ea-884a-77a4d508e014.png)

**Comment by jiangz222** [comment]
Bulk() is a  experimental in `mgo`, we will consider it ,thanks!

**Comment by jiangz222** [comment]
welcome to wechat group

![avatar](http://pgo8q04yu.bkt.clouddn.com/qmgoG)

**Comment by xen0n** [comment]
I think this is dupe of #98?

**Comment by jiangz222** [comment]
Fixed by #153 #151
