### ISSUE TITLE
Hooks

### ISSUE THREAD

**Issue by jiangz222** [qiniu/qmgo#63]
Check out [hooks in gorm](http://gorm.io/docs/hooks.html)

Hooks may be a solution to #62 , wrapper the user's hooks with qmgo hooks, so qmgo hooks update default fields, then call user's hooks.

**Comment by mirusky** [comment]
Is a good proposal to use Hooks and ways to register new functionsName as hooks like [gorm](http://gorm.io/docs/write_plugins.html#Register-a-new-callback)

**Comment by jiangz222** [comment]
> Is a good proposal to use Hooks and ways to register new functionsName as hooks like [gorm](http://gorm.io/docs/write_plugins.html#Register-a-new-callback)

Got it！Thanks!
Long way to go! Let's do the basic hooks in the first step!
