### ISSUE TITLE
Hooks v2

### ISSUE THREAD

**Issue by jiangz222** [qiniu/qmgo#72]
#71 implement the Hooks v1 in qmgo: [More about hooks](https://github.com/qiniu/qmgo/wiki/Hooks) | [Hooks详情介绍](https://github.com/qiniu/qmgo/wiki/Hooks--(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87))

But more jobs need to do:
- #73 Can't change documents in hooks, which also make feature: `default and custom fields in update operation` is blocked now #62 
- Now we use options to pass in hooks, Is there any more elegant way?  specially in current version of qmgo, no document is passed in in `Update` operation.

**Comment by mirusky** [comment]
I will try to help, if you can explain to me what you did in hooks v1 will be helpfull

**Comment by jiangz222** [comment]
> I will try to help, if you can explain to me what you did in hooks v1 will be helpfull

Thanks！
You can check pr #71  first, and follow the [manual](https://github.com/qiniu/qmgo/wiki/Hooks) and examples in [collection_hook_test.go](https://github.com/qiniu/qmgo/blob/master/collection_hook_test.go) to dig the codes.
Basically, when we are doing a certain database operation, we create a struct which implements the  hook interface, then pass in it by option. Qmgo will call back these struct methods.

**Comment by mirusky** [comment]
Hi thanks for explain the beginning!

Now i'm currently trying to implement a better way to hooks... And I liked this one:

```go
package hook

type Operation int

const (
	Insert Operation = iota
	Update
	Delete
)

type Moment int

const (
	After Moment = iota
	Before
)

// Hook ...
type Hook struct {
	FuncName string // FuncName represent default name to call
	Prior    int    // Prior represent the priority of this hook
}

// Processor ...
type Processor struct {
	Hooks map[Moment]map[Operation]Hook
}
```

So I'm thinking to create a `generic caller` to call FuncName in struct ... And then we could use it somethink like:

```go
// InsertOne insert one document into the collection
// Reference: https://docs.mongodb.com/manual/reference/command/insert/
func (c *Collection) InsertOne(ctx context.Context, doc interface{}, opts ...qOpts.InsertOneOptions) (result *InsertOneResult, err error) {
	hook.Call(hook.Processor[After][Insert], &doc)
	res, err := c.collection.InsertOne(ctx, doc)
	if res != nil {
		result = &InsertOneResult{InsertedID: res.InsertedID}
	}
	hook.Call(hook.Processor[Before][Insert], &doc)
	return
}
```

[Here ](https://play.golang.org/p/5QTnKXdm0N7) is an example of what i'm calling `generic caller`

**Comment by jiangz222** [comment]
> Hi thanks for explain the beginning!
> 
> Now i'm currently trying to implement a better way to hooks... And I liked this one:
> 
> ```go
> package hook
> 
> type Operation int
> 
> const (
> 	Insert Operation = iota
> 	Update
> 	Delete
> )
> 
> type Moment int
> 
> const (
> 	After Moment = iota
> 	Before
> )
> 
> // Hook ...
> type Hook struct {
> 	FuncName string // FuncName represent default name to call
> 	Prior    int    // Prior represent the priority of this hook
> }
> 
> // Processor ...
> type Processor struct {
> 	Hooks map[Moment]map[Operation]Hook
> }
> ```
> 
> So I'm thinking to create a `generic caller` to call FuncName in struct ... And then we could use it somethink like:
> 
> ```go
> // InsertOne insert one document into the collection
> // Reference: https://docs.mongodb.com/manual/reference/command/insert/
> func (c *Collection) InsertOne(ctx context.Context, doc interface{}, opts ...qOpts.InsertOneOptions) (result *InsertOneResult, err error) {
> 	hook.Call(hook.Processor[After][Insert], &doc)
> 	res, err := c.collection.InsertOne(ctx, doc)
> 	if res != nil {
> 		result = &InsertOneResult{InsertedID: res.InsertedID}
> 	}
> 	hook.Call(hook.Processor[Before][Insert], &doc)
> 	return
> }
> ```
> 
> [Here ](https://play.golang.org/p/wgmFlsBywFX) is an example of what i'm calling `generic caller`, note when the method does not exist we could just ignore or log it

Thanks!
To user, what's the difference in your solution?
please note that: no document struct is passed in in Update operation.

**Comment by mirusky** [comment]
@jiangz222 I believe the way I'm coding, it is more advantageous for the user because he does not need to pass the option in each operation, he could just register hooks before client operations and that's it. All the hard work is for `processor` and hook `call` method.

I haven't tested it yet, but I believe we could use a struct in second parameter in Update operation. Or we can refactor to add more flexibility...

**Comment by jiangz222** [comment]
@mirusky Actually, the current implement of hook is flexible. the real problem is  #73.
For example, because `insert operation` support struct of document, we can use insert operation  like below after make little changes in `InsertOne`:
```go
type UserHook struct {
}
func (u *UserHook) BeforeInsert() error {
}
func (u *UserHook) AfterInsert() error {
}


func (c *Collection) InsertOne(ctx context.Context, doc interface{}) (result *InsertOneResult, err error) {
      // use doc directly and hook callback method of struct of doc.(UserType)
	if err = hook.Do(doc, hook.BeforeInsert); err != nil {
		return
	}
	res, err := c.collection.InsertOne(ctx, doc)
	if res != nil {
		result = &InsertOneResult{InsertedID: res.InsertedID}
	}
	if err = hook.Do(doc, hook.AfterInsert); err != nil {
		return
	}

	return
}
```
Above solution is supported and is the first choice to hook, and I already test it, you can check more [here](https://github.com/qiniu/qmgo/tree/master/hook).
But the `update operation` doesn't support the document struct as parameter yet, so `options` become the hook v1 solution.

**Comment by mirusky** [comment]
So how to resolve a multiple "BeforeInsert" hook? Like user has custom Methods in struct, so he needs use "BeforeInsert" Method to call all others?

Like:
```go
type UserHook struct {
}
func (u *UserHook) BeforeInsert() error {
  u.MyCustomHook()
  u.MyCustomHook2()
}
func (u *UserHook) AfterInsert() error {
}
func (u *UserHook) MyCustomHook() error {
}
func (u *UserHook) MyCustomHook2() error {
}
```

**Comment by jiangz222** [comment]
@mirusky 
Yes，I think interface(like BeforeInsert) should be simple, you can do whatever you want in it.

**Comment by jiangz222** [comment]
Because Qmgo is not a typical ORM, so After #78 supported（hooks of  `InsertOne`、`InsertMany` and `UpdateWithDocument` can work without options), close this issue at this stage.
