### ISSUE TITLE
Support collection.bulkWrite() 

### ISSUE THREAD

**Issue by jiangz222** [qiniu/qmgo#98]
[Reference](https://docs.mongodb.com/manual/reference/method/db.collection.bulkWrite/#db.collection.bulkWrite)
MongoDB official driver has `collection.bulkWrite()`

**Comment by xen0n** [comment]
We need this for one *single* operation during our porting. I think doing `coll.CloneCollection()` to expose the underlying driver object suffices?

**Comment by xen0n** [comment]
Note: I'm currently taking this, maybe my work will be ready in a week or so.

If I cannot allocate enough time for the porting I'll similarly announce here.

**Comment by xen0n** [comment]
There is the problem of supporting hooks for operations inside a bulk. I need to spend a bit time investigating how this could be done, even [gorm wasn't able to do it before v2](https://github.com/go-gorm/gorm/issues/255).

**Comment by jiangz222** [comment]
> There is the problem of supporting hooks for operations inside a bulk. I need to spend a bit time investigating how this could be done, even [gorm wasn't able to do it before v2](https://github.com/go-gorm/gorm/issues/255).

Maybe we can support bulk first, support hooks in next release.

**Comment by xen0n** [comment]
> > There is the problem of supporting hooks for operations inside a bulk. I need to spend a bit time investigating how this could be done, even [gorm wasn't able to do it before v2](https://github.com/go-gorm/gorm/issues/255).
> 
> Maybe we can support bulk first, support hooks in next release.

Then we need a way to prevent users from accidentally depending on the incomplete feature, or at very least inform them about the limitation. Do you think mentioning it in the docs would be enough? Or returning error in case the objects implement the hook methods?

**Comment by jiangz222** [comment]
> > > There is the problem of supporting hooks for operations inside a bulk. I need to spend a bit time investigating how this could be done, even [gorm wasn't able to do it before v2](https://github.com/go-gorm/gorm/issues/255).
> > 
> > 
> > Maybe we can support bulk first, support hooks in next release.
> 
> Then we need a way to prevent users from accidentally depending on the incomplete feature, or at very least inform them about the limitation. Do you think mentioning it in the docs would be enough? Or returning error in case the objects implement the hook methods?

The interfaces that support hooks has been clearly defined in the wiki, which I think is enough for now.
CRUD are basic functions, hook is an additional function, the lack of additional functions does not affect the use of basic functions.

**Comment by xen0n** [comment]
> > > > There is the problem of supporting hooks for operations inside a bulk. I need to spend a bit time investigating how this could be done, even [gorm wasn't able to do it before v2](https://github.com/go-gorm/gorm/issues/255).
> > > 
> > > 
> > > Maybe we can support bulk first, support hooks in next release.
> > 
> > 
> > Then we need a way to prevent users from accidentally depending on the incomplete feature, or at very least inform them about the limitation. Do you think mentioning it in the docs would be enough? Or returning error in case the objects implement the hook methods?
> 
> The interfaces that support hooks has been clearly defined in the wiki, which I think is enough for now.
> CRUD are basic functions, hook is an additional function, the lack of additional functions does not affect the use of basic functions.

Changing behavior like this between versions, is technically considered breakage. I'd prefer not letting hook-enabled entity types slip in though, this way users are clearly aware that "something is different with bulk ops". They're free to revisit the code once hooks are properly supported, and calls with such types no longer errors.

**Comment by jiangz222** [comment]
> I'd prefer not letting hook-enabled entity types slip in though

Yes，Agree！

**Comment by xen0n** [comment]
A preliminary implementation is at #151.

The guard against hooks is unnecessary due to the current way to invoke them: without the `opts` parameter on bulk ops' signatures, there's no way to pass in those hooks.
